name: cowgirl
favicon: null
layout_spectrum: 1
title: Cowgirl
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: eff33227-c9ef-48cb-a0e7-a1caad7eabba
    url: null
